---
- hosts: localhost
  vars_prompt:
  - name: fah_username
    prompt: "What is your FAH username?"
    default: "Anonymous"
    private: no

  - name: fah_team
    prompt: "Do you want to join a team?"
    default: "0"
    private: no

  - name: fah_gpu
    prompt: "Does your computer have a NVIDIA GPU with the latest drivers installed? (true or false)"
    default: "false"
    private: no

  vars:
    fah_pre_packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    fah_post_packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - nvidia-container-toolkit
    fah_gpu_packages:
    - dkms
    - build-essential
    - nvidia-driver-440
    fah_apt_keys:
    - https://download.docker.com/linux/ubuntu/gpg
    - https://nvidia.github.io/nvidia-docker/gpgkey
    fah_nvidia_sources: https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list
    fah_docker_deb: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    fah_image: amalic/nvdocker-folding-home
    
  tasks:
  - name: Install pre-packages
    package:
      name: "{{ item }}"
      state: latest
    with_items: "{{ fah_pre_packages }}" 

  - name: Add GPG keys
    apt_key:
      url: "{{ item }}"
      state: present
    with_items: "{{ fah_apt_keys }}"

  - name: Add NVIDIA repo
    get_url:
      url: "{{ fah_nvidia_sources }}"
      dest: /etc/apt/sources.list.d/nvidia-docker.list

  - name: Add Docker CE repo
    apt_repository:
      repo: "{{ fah_docker_deb }}"
      state: present

  - name: Install post-packages
    package:
      name: "{{ item }}"
      state: latest
    with_items: "{{ fah_post_packages }}" 

  - name: Inspect if NVIDIA driver is available
    command: modinfo nvidia
    ignore_errors: yes
    register: fah_gpu_module

  - name: Install and enable NVIDIA GPU
    block:
    - name: Add graphics-driver repo
      apt_repository:
        repo: ppa:graphics-drivers/ppa

    - name: Install gpu-packages
      package:
        name: "{{ item }}"
        state: latest
      with_items: "{{ fah_gpu_packages }}" 

    when: fah_gpu == "true" and fah_gpu_module.rc == "1"

  - name: Ensure kernel modules are loaded
    command: modprobe nvidia
    when: fah_gpu == "true"

  - name: Identify runtime mode
    stat:
      path: /rofs
    register: fah_cow

  - name: Relocate /var/lib/docker if running live
    block:
    - lineinfile:
        line: ExecStart=/usr/bin/dockerd -g /tmp/docker -H fd:// --containerd=/run/containerd/containerd.sock
        path: /lib/systemd/system/docker.service
        regexp: '^ExecStart='
    - command: systemctl daemon-reload
    when: fah_cow.stat.exists

  - name: Ensure no current workload is running
    shell: docker rm -f fah || true

  - name: Start FAH client (CPU)
    command: docker run --name fah 
             -e USE_GPU=false 
             -e USERNAME={{ fah_username }}
             -e TEAM={{ fah_team }}
             --restart unless-stopped 
             -p 8080:7396 -d {{ fah_image }}
    when: fah_gpu == "false"

  - name: Start FAH client (GPU)
    command: docker run --name fah 
             -e USERNAME={{ fah_username }}
             -e TEAM={{ fah_team }}
             --gpus all
             --restart unless-stopped 
             -p 8080:7396 -d {{ fah_image }}
    when: fah_gpu == "true"
